project:
  type: book
  output-dir: docs

book:
  title: "R faculty workshop"

  chapters:
    - index.qmd
    - part: "Introduction to R"
      chapters:
        - 1_1_intro-to-r.qmd
        - 1_2_basics.qmd
        - 1_3_working-with-data.qmd
    - part: "Teaching with R"
      chapters:
        - 2_1_general-approach.qmd
        - 2_2_quarto.qmd
        - 2_3_problem-sets.qmd

format:
  html:
    theme:
      light: [flatly, custom.scss]
      dark:  [darkly, custom.scss]
    link-external-newwindow: true
  pdf:
    toc: false



editor: visual
