project:
  type: book
  output-dir: pdf

book:
  title: "R Faculty Workshop"
  chapters:
    - index.qmd
    - 1_1_intro-to-r.qmd
    - 1_2_basics.qmd
    - 1_3_working-with-data.qmd
    - 2_1_general-approach.qmd
    - 2_2_quarto.qmd
    - 2_3_problem-sets.qmd

format:
  pdf:
    toc: false
    df-print: kable
