project:
  type: website
  output-dir: docs
  pre-render: _render-pdf.R
  resources: resources/


website:
  title: "R Faculty Workshop"
  sidebar:
    style: floating
    contents:
      - index.qmd
      - section: "Day 1: Intro to R"
        contents:
          - 1_1_intro-to-r.qmd
          - 1_2_basics.qmd
          - 1_3_working-with-data.qmd
          - 1_4_other-things.qmd
      - section: "Day 2: Teaching with R"
        contents:
          - 2_1_general-approach.qmd
          - 2_2_posit-cloud.qmd
          - 2_3_quarto.qmd
          - 2_4_course-materials.qmd

format:
  html:
    toc: true
    df-print: kable
    code-line-numbers: false
    format-links: [revealjs]
    theme: cosmo
    link-external-newwindow: true
  revealjs:
    slide-level: 4
    code-line-numbers: false
    df-print: kable
    chalkboard: true

execute:
  echo: true

editor: visual
