
rm(list=ls(all=TRUE))	

install.packages("dplyr", dependencies=T)
install.packages("ggplot2", dependencies=T)
install.packages("foreign", dependencies=T)
install.packages("xtable", dependencies = T)
install.packages("stargazer", dependencies = T)
install.packages("arm", dependencies = T)
install.packages("modeest", dependencies=T)
install.packages("lmtest", dependencies=T)
install.packages("sandwich", dependencies=T)
install.packages("DataCombine", dependencies=T)
install.packages("car", dependencies=T)
install.packages("knitr", dependencies=T)